// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArfyDL0RIUrXm-rBQVTKPHZD6EoZt9Dr8',
    appId: '1:27380353617:web:d7a7914e58347f15e04670',
    messagingSenderId: '27380353617',
    projectId: 'cosons-b1928',
    authDomain: 'cosons-b1928.firebaseapp.com',
    storageBucket: 'cosons-b1928.appspot.com',
    measurementId: 'G-HMKN3PEN9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDoiDZ8UV3kVqTR9oB75s7Arhf9y9pVDE',
    appId: '1:27380353617:android:b6d8989e5d4c4a71e04670',
    messagingSenderId: '27380353617',
    projectId: 'cosons-b1928',
    storageBucket: 'cosons-b1928.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_oMLTV-taK9YDAhb73y3hB6R4Rh-AAB0',
    appId: '1:27380353617:ios:d6f1e1fa6ef5b8c2e04670',
    messagingSenderId: '27380353617',
    projectId: 'cosons-b1928',
    storageBucket: 'cosons-b1928.appspot.com',
    iosBundleId: 'com.example.cosons',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_oMLTV-taK9YDAhb73y3hB6R4Rh-AAB0',
    appId: '1:27380353617:ios:4fe99c6b17a04283e04670',
    messagingSenderId: '27380353617',
    projectId: 'cosons-b1928',
    storageBucket: 'cosons-b1928.appspot.com',
    iosBundleId: 'com.example.cosons.RunnerTests',
  );
}
